<?php
/**
 * @file WDG Support Monitor
 * @author Web Development Group (WDG) <https://www.webdevelopmentgroup.com>
 */

use \Drupal\wdg_support_monitor\SupportMonitor;

/**
 * Implements hook_cron().
 */
function wdg_support_monitor_cron() {
  $frequency = 60 * 60 * 12; // 12 hours

  $wdg_support_monitor = SupportMonitor::get_instance();

  $last_run = $wdg_support_monitor->get_last_run();
  $current_time = \Drupal::time()->getRequestTime(); // Updated for Drupal 10
  
  if (is_null($last_run) || empty($last_run->success) || empty($last_run->timestamp) || $current_time - $last_run->timestamp > $frequency) {
    $wdg_support_monitor->update(FALSE);
  }
}
