<?php
/**
 * @file Install
 * @author Web Development Group (WDG) <https://www.webdevelopmentgroup.com>
 */

use Drupal\wdg_support_monitor\SupportMonitor;

/**
 * Implements hook_install().
 */
function wdg_support_monitor_install() {
	\Drupal::state()->set( SupportMonitor::LAST_RUN_KEY, NULL );
}

/**
 * Implements hook_uninstall().
 */
function wdg_support_monitor_uninstall() {
	\Drupal::state()->delete( SupportMonitor::LAST_RUN_KEY );
}
